/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/ZFileGridItem copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZButton: typeof import('./src/components/ZButton.vue')['default']
    ZFileGridItem: typeof import('./src/components/ZFileList/ZFileGridItem.vue')['default']
    ZFileList: typeof import('./src/components/ZFileList/ZFileList.vue')['default']
    ZFileListItem: typeof import('./src/components/ZFileList/ZFileListItem.vue')['default']
  }
}
